# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _GccIter.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GccIter', [dirname(__file__)])
        except ImportError:
            import _GccIter
            return _GccIter
        if fp is not None:
            try:
                _mod = imp.load_module('_GccIter', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GccIter = swig_import_helper()
    del swig_import_helper
else:
    import _GccIter
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GccIter.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_GccIter.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_GccIter.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_GccIter.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_GccIter.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_GccIter.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_GccIter.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_GccIter.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_GccIter.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_GccIter.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_GccIter.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_GccIter.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_GccIter.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_GccIter.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_GccIter.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_GccIter.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_GccIter.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _GccIter.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


_GccIter.GccIter_CuCuCu_swigconstant(_GccIter)
GccIter_CuCuCu = _GccIter.GccIter_CuCuCu

_GccIter.GccIter_CiCuCu_swigconstant(_GccIter)
GccIter_CiCuCu = _GccIter.GccIter_CiCuCu

_GccIter.GccIter_CiCiCu_swigconstant(_GccIter)
GccIter_CiCiCu = _GccIter.GccIter_CiCiCu

_GccIter.GccIter_CiLiCu_swigconstant(_GccIter)
GccIter_CiLiCu = _GccIter.GccIter_CiLiCu

_GccIter.GccIter_LiLiCu_swigconstant(_GccIter)
GccIter_LiLiCu = _GccIter.GccIter_LiLiCu

_GccIter.GccIter_LiCuCu_swigconstant(_GccIter)
GccIter_LiCuCu = _GccIter.GccIter_LiCuCu

_GccIter.GccIter_CuCuOnCu_swigconstant(_GccIter)
GccIter_CuCuOnCu = _GccIter.GccIter_CuCuOnCu

_GccIter.GccIter_CiCuOnCu_swigconstant(_GccIter)
GccIter_CiCuOnCu = _GccIter.GccIter_CiCuOnCu

_GccIter.GccIter_LiCuOnCu_swigconstant(_GccIter)
GccIter_LiCuOnCu = _GccIter.GccIter_LiCuOnCu

_GccIter.GccIter_CuPtOnCu_swigconstant(_GccIter)
GccIter_CuPtOnCu = _GccIter.GccIter_CuPtOnCu

_GccIter.GccIter_CuCuOnLi_swigconstant(_GccIter)
GccIter_CuCuOnLi = _GccIter.GccIter_CuCuOnLi

_GccIter.GccIter_CiCuOnLi_swigconstant(_GccIter)
GccIter_CiCuOnLi = _GccIter.GccIter_CiCuOnLi

_GccIter.GccIter_LiCuOnLi_swigconstant(_GccIter)
GccIter_LiCuOnLi = _GccIter.GccIter_LiCuOnLi

_GccIter.GccIter_CuPtOnLi_swigconstant(_GccIter)
GccIter_CuPtOnLi = _GccIter.GccIter_CuPtOnLi

_GccIter.GccIter_CuCuOnCi_swigconstant(_GccIter)
GccIter_CuCuOnCi = _GccIter.GccIter_CuCuOnCi

_GccIter.GccIter_CiCuOnCi_swigconstant(_GccIter)
GccIter_CiCuOnCi = _GccIter.GccIter_CiCuOnCi

_GccIter.GccIter_LiCuOnCi_swigconstant(_GccIter)
GccIter_LiCuOnCi = _GccIter.GccIter_LiCuOnCi

_GccIter.GccIter_CuPtOnCi_swigconstant(_GccIter)
GccIter_CuPtOnCi = _GccIter.GccIter_CuPtOnCi

_GccIter.GccIter_CuCu_swigconstant(_GccIter)
GccIter_CuCu = _GccIter.GccIter_CuCu

_GccIter.GccIter_CiCu_swigconstant(_GccIter)
GccIter_CiCu = _GccIter.GccIter_CiCu


