# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _GeomAbs.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GeomAbs', [dirname(__file__)])
        except ImportError:
            import _GeomAbs
            return _GeomAbs
        if fp is not None:
            try:
                _mod = imp.load_module('_GeomAbs', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GeomAbs = swig_import_helper()
    del swig_import_helper
else:
    import _GeomAbs
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GeomAbs.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_GeomAbs.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_GeomAbs.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_GeomAbs.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_GeomAbs.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_GeomAbs.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_GeomAbs.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_GeomAbs.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_GeomAbs.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_GeomAbs.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_GeomAbs.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_GeomAbs.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_GeomAbs.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_GeomAbs.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_GeomAbs.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_GeomAbs.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_GeomAbs.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _GeomAbs.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


_GeomAbs.GeomAbs_NonUniform_swigconstant(_GeomAbs)
GeomAbs_NonUniform = _GeomAbs.GeomAbs_NonUniform

_GeomAbs.GeomAbs_Uniform_swigconstant(_GeomAbs)
GeomAbs_Uniform = _GeomAbs.GeomAbs_Uniform

_GeomAbs.GeomAbs_QuasiUniform_swigconstant(_GeomAbs)
GeomAbs_QuasiUniform = _GeomAbs.GeomAbs_QuasiUniform

_GeomAbs.GeomAbs_PiecewiseBezier_swigconstant(_GeomAbs)
GeomAbs_PiecewiseBezier = _GeomAbs.GeomAbs_PiecewiseBezier

_GeomAbs.GeomAbs_PolylineForm_swigconstant(_GeomAbs)
GeomAbs_PolylineForm = _GeomAbs.GeomAbs_PolylineForm

_GeomAbs.GeomAbs_CircularForm_swigconstant(_GeomAbs)
GeomAbs_CircularForm = _GeomAbs.GeomAbs_CircularForm

_GeomAbs.GeomAbs_EllipticForm_swigconstant(_GeomAbs)
GeomAbs_EllipticForm = _GeomAbs.GeomAbs_EllipticForm

_GeomAbs.GeomAbs_HyperbolicForm_swigconstant(_GeomAbs)
GeomAbs_HyperbolicForm = _GeomAbs.GeomAbs_HyperbolicForm

_GeomAbs.GeomAbs_ParabolicForm_swigconstant(_GeomAbs)
GeomAbs_ParabolicForm = _GeomAbs.GeomAbs_ParabolicForm

_GeomAbs.GeomAbs_OtherCurveForm_swigconstant(_GeomAbs)
GeomAbs_OtherCurveForm = _GeomAbs.GeomAbs_OtherCurveForm

_GeomAbs.GeomAbs_Line_swigconstant(_GeomAbs)
GeomAbs_Line = _GeomAbs.GeomAbs_Line

_GeomAbs.GeomAbs_Circle_swigconstant(_GeomAbs)
GeomAbs_Circle = _GeomAbs.GeomAbs_Circle

_GeomAbs.GeomAbs_Ellipse_swigconstant(_GeomAbs)
GeomAbs_Ellipse = _GeomAbs.GeomAbs_Ellipse

_GeomAbs.GeomAbs_Hyperbola_swigconstant(_GeomAbs)
GeomAbs_Hyperbola = _GeomAbs.GeomAbs_Hyperbola

_GeomAbs.GeomAbs_Parabola_swigconstant(_GeomAbs)
GeomAbs_Parabola = _GeomAbs.GeomAbs_Parabola

_GeomAbs.GeomAbs_BezierCurve_swigconstant(_GeomAbs)
GeomAbs_BezierCurve = _GeomAbs.GeomAbs_BezierCurve

_GeomAbs.GeomAbs_BSplineCurve_swigconstant(_GeomAbs)
GeomAbs_BSplineCurve = _GeomAbs.GeomAbs_BSplineCurve

_GeomAbs.GeomAbs_OtherCurve_swigconstant(_GeomAbs)
GeomAbs_OtherCurve = _GeomAbs.GeomAbs_OtherCurve

_GeomAbs.GeomAbs_IsoU_swigconstant(_GeomAbs)
GeomAbs_IsoU = _GeomAbs.GeomAbs_IsoU

_GeomAbs.GeomAbs_IsoV_swigconstant(_GeomAbs)
GeomAbs_IsoV = _GeomAbs.GeomAbs_IsoV

_GeomAbs.GeomAbs_NoneIso_swigconstant(_GeomAbs)
GeomAbs_NoneIso = _GeomAbs.GeomAbs_NoneIso

_GeomAbs.GeomAbs_Arc_swigconstant(_GeomAbs)
GeomAbs_Arc = _GeomAbs.GeomAbs_Arc

_GeomAbs.GeomAbs_Tangent_swigconstant(_GeomAbs)
GeomAbs_Tangent = _GeomAbs.GeomAbs_Tangent

_GeomAbs.GeomAbs_Intersection_swigconstant(_GeomAbs)
GeomAbs_Intersection = _GeomAbs.GeomAbs_Intersection

_GeomAbs.GeomAbs_C0_swigconstant(_GeomAbs)
GeomAbs_C0 = _GeomAbs.GeomAbs_C0

_GeomAbs.GeomAbs_G1_swigconstant(_GeomAbs)
GeomAbs_G1 = _GeomAbs.GeomAbs_G1

_GeomAbs.GeomAbs_C1_swigconstant(_GeomAbs)
GeomAbs_C1 = _GeomAbs.GeomAbs_C1

_GeomAbs.GeomAbs_G2_swigconstant(_GeomAbs)
GeomAbs_G2 = _GeomAbs.GeomAbs_G2

_GeomAbs.GeomAbs_C2_swigconstant(_GeomAbs)
GeomAbs_C2 = _GeomAbs.GeomAbs_C2

_GeomAbs.GeomAbs_C3_swigconstant(_GeomAbs)
GeomAbs_C3 = _GeomAbs.GeomAbs_C3

_GeomAbs.GeomAbs_CN_swigconstant(_GeomAbs)
GeomAbs_CN = _GeomAbs.GeomAbs_CN

_GeomAbs.GeomAbs_PlanarForm_swigconstant(_GeomAbs)
GeomAbs_PlanarForm = _GeomAbs.GeomAbs_PlanarForm

_GeomAbs.GeomAbs_ConicalForm_swigconstant(_GeomAbs)
GeomAbs_ConicalForm = _GeomAbs.GeomAbs_ConicalForm

_GeomAbs.GeomAbs_CylindricalForm_swigconstant(_GeomAbs)
GeomAbs_CylindricalForm = _GeomAbs.GeomAbs_CylindricalForm

_GeomAbs.GeomAbs_ToroidalForm_swigconstant(_GeomAbs)
GeomAbs_ToroidalForm = _GeomAbs.GeomAbs_ToroidalForm

_GeomAbs.GeomAbs_SphericalForm_swigconstant(_GeomAbs)
GeomAbs_SphericalForm = _GeomAbs.GeomAbs_SphericalForm

_GeomAbs.GeomAbs_RevolutionForm_swigconstant(_GeomAbs)
GeomAbs_RevolutionForm = _GeomAbs.GeomAbs_RevolutionForm

_GeomAbs.GeomAbs_RuledForm_swigconstant(_GeomAbs)
GeomAbs_RuledForm = _GeomAbs.GeomAbs_RuledForm

_GeomAbs.GeomAbs_QuadricForm_swigconstant(_GeomAbs)
GeomAbs_QuadricForm = _GeomAbs.GeomAbs_QuadricForm

_GeomAbs.GeomAbs_OtherSurfaceForm_swigconstant(_GeomAbs)
GeomAbs_OtherSurfaceForm = _GeomAbs.GeomAbs_OtherSurfaceForm

_GeomAbs.GeomAbs_Plane_swigconstant(_GeomAbs)
GeomAbs_Plane = _GeomAbs.GeomAbs_Plane

_GeomAbs.GeomAbs_Cylinder_swigconstant(_GeomAbs)
GeomAbs_Cylinder = _GeomAbs.GeomAbs_Cylinder

_GeomAbs.GeomAbs_Cone_swigconstant(_GeomAbs)
GeomAbs_Cone = _GeomAbs.GeomAbs_Cone

_GeomAbs.GeomAbs_Sphere_swigconstant(_GeomAbs)
GeomAbs_Sphere = _GeomAbs.GeomAbs_Sphere

_GeomAbs.GeomAbs_Torus_swigconstant(_GeomAbs)
GeomAbs_Torus = _GeomAbs.GeomAbs_Torus

_GeomAbs.GeomAbs_BezierSurface_swigconstant(_GeomAbs)
GeomAbs_BezierSurface = _GeomAbs.GeomAbs_BezierSurface

_GeomAbs.GeomAbs_BSplineSurface_swigconstant(_GeomAbs)
GeomAbs_BSplineSurface = _GeomAbs.GeomAbs_BSplineSurface

_GeomAbs.GeomAbs_SurfaceOfRevolution_swigconstant(_GeomAbs)
GeomAbs_SurfaceOfRevolution = _GeomAbs.GeomAbs_SurfaceOfRevolution

_GeomAbs.GeomAbs_SurfaceOfExtrusion_swigconstant(_GeomAbs)
GeomAbs_SurfaceOfExtrusion = _GeomAbs.GeomAbs_SurfaceOfExtrusion

_GeomAbs.GeomAbs_OffsetSurface_swigconstant(_GeomAbs)
GeomAbs_OffsetSurface = _GeomAbs.GeomAbs_OffsetSurface

_GeomAbs.GeomAbs_OtherSurface_swigconstant(_GeomAbs)
GeomAbs_OtherSurface = _GeomAbs.GeomAbs_OtherSurface

_GeomAbs.GeomAbs_SameUV_swigconstant(_GeomAbs)
GeomAbs_SameUV = _GeomAbs.GeomAbs_SameUV

_GeomAbs.GeomAbs_SameU_swigconstant(_GeomAbs)
GeomAbs_SameU = _GeomAbs.GeomAbs_SameU

_GeomAbs.GeomAbs_SameV_swigconstant(_GeomAbs)
GeomAbs_SameV = _GeomAbs.GeomAbs_SameV

_GeomAbs.GeomAbs_OppositeUV_swigconstant(_GeomAbs)
GeomAbs_OppositeUV = _GeomAbs.GeomAbs_OppositeUV


