# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _GeomAdaptor.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GeomAdaptor', [dirname(__file__)])
        except ImportError:
            import _GeomAdaptor
            return _GeomAdaptor
        if fp is not None:
            try:
                _mod = imp.load_module('_GeomAdaptor', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GeomAdaptor = swig_import_helper()
    del swig_import_helper
else:
    import _GeomAdaptor
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GeomAdaptor.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_GeomAdaptor.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_GeomAdaptor.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_GeomAdaptor.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_GeomAdaptor.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_GeomAdaptor.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_GeomAdaptor.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_GeomAdaptor.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_GeomAdaptor.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_GeomAdaptor.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_GeomAdaptor.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _GeomAdaptor.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import OCC.Adaptor3d
import OCC.Standard
import OCC.GeomAbs
import OCC.TColStd
import OCC.TCollection
import OCC.MMgt
import OCC.gp
import OCC.Geom
import OCC.TColgp
import OCC.Adaptor2d
import OCC.Geom2d
import OCC.TopAbs
import OCC.math
class geomadaptor(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def MakeCurve(*args):
        """
        * Inherited from GHCurve. Provides a curve handled by reference. Build a Geom_Curve using the informations from the Curve from Adaptor3d

        :param C:
        :type C: Adaptor3d_Curve &
        :rtype: Handle_Geom_Curve

        """
        return _GeomAdaptor.geomadaptor_MakeCurve(*args)

    MakeCurve = staticmethod(MakeCurve)

    def MakeSurface(*args):
        """
        * Build a Geom_Surface using the informations from the Surface from Adaptor3d

        :param S:
        :type S: Adaptor3d_Surface &
        :rtype: Handle_Geom_Surface

        """
        return _GeomAdaptor.geomadaptor_MakeSurface(*args)

    MakeSurface = staticmethod(MakeSurface)

    def __init__(self):
        _GeomAdaptor.geomadaptor_swiginit(self, _GeomAdaptor.new_geomadaptor())

    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


geomadaptor._kill_pointed = new_instancemethod(_GeomAdaptor.geomadaptor__kill_pointed, None, geomadaptor)
geomadaptor_swigregister = _GeomAdaptor.geomadaptor_swigregister
geomadaptor_swigregister(geomadaptor)

def geomadaptor_MakeCurve(*args):
    """
    * Inherited from GHCurve. Provides a curve handled by reference. Build a Geom_Curve using the informations from the Curve from Adaptor3d

    :param C:
    :type C: Adaptor3d_Curve &
    :rtype: Handle_Geom_Curve

    """
    return _GeomAdaptor.geomadaptor_MakeCurve(*args)

def geomadaptor_MakeSurface(*args):
    """
    * Build a Geom_Surface using the informations from the Surface from Adaptor3d

    :param S:
    :type S: Adaptor3d_Surface &
    :rtype: Handle_Geom_Surface

    """
    return _GeomAdaptor.geomadaptor_MakeSurface(*args)

class GeomAdaptor_Curve(OCC.Adaptor3d.Adaptor3d_Curve):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param C:
        :type C: Handle_Geom_Curve &
        :rtype: None

        * ConstructionError is raised if Ufirst>Ulast

        :param C:
        :type C: Handle_Geom_Curve &
        :param UFirst:
        :type UFirst: float
        :param ULast:
        :type ULast: float
        :rtype: None

        """
        _GeomAdaptor.GeomAdaptor_Curve_swiginit(self, _GeomAdaptor.new_GeomAdaptor_Curve(*args))

    def Load(self, *args):
        """
        :param C:
        :type C: Handle_Geom_Curve &
        :rtype: None

        * ConstructionError is raised if Ufirst>Ulast

        :param C:
        :type C: Handle_Geom_Curve &
        :param UFirst:
        :type UFirst: float
        :param ULast:
        :type ULast: float
        :rtype: None

        """
        return _GeomAdaptor.GeomAdaptor_Curve_Load(self, *args)


    def Curve(self, *args):
        """
        * Provides a curve inherited from Hcurve from Adaptor. This is inherited to provide easy to use constructors.

        :rtype: Handle_Geom_Curve

        """
        return _GeomAdaptor.GeomAdaptor_Curve_Curve(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GeomAdaptor_Curve.Load = new_instancemethod(_GeomAdaptor.GeomAdaptor_Curve_Load, None, GeomAdaptor_Curve)
GeomAdaptor_Curve.Curve = new_instancemethod(_GeomAdaptor.GeomAdaptor_Curve_Curve, None, GeomAdaptor_Curve)
GeomAdaptor_Curve._kill_pointed = new_instancemethod(_GeomAdaptor.GeomAdaptor_Curve__kill_pointed, None, GeomAdaptor_Curve)
GeomAdaptor_Curve_swigregister = _GeomAdaptor.GeomAdaptor_Curve_swigregister
GeomAdaptor_Curve_swigregister(GeomAdaptor_Curve)

class GeomAdaptor_GHCurve(OCC.Adaptor3d.Adaptor3d_HCurve):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param C:
        :type C: GeomAdaptor_Curve &
        :rtype: None

        """
        _GeomAdaptor.GeomAdaptor_GHCurve_swiginit(self, _GeomAdaptor.new_GeomAdaptor_GHCurve(*args))

    def Set(self, *args):
        """
        :param C:
        :type C: GeomAdaptor_Curve &
        :rtype: None

        """
        return _GeomAdaptor.GeomAdaptor_GHCurve_Set(self, *args)


    def ChangeCurve(self, *args):
        """
        :rtype: GeomAdaptor_Curve

        """
        return _GeomAdaptor.GeomAdaptor_GHCurve_ChangeCurve(self, *args)


    def _kill_pointed(self):
        """_kill_pointed(GeomAdaptor_GHCurve self)"""
        return _GeomAdaptor.GeomAdaptor_GHCurve__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(GeomAdaptor_GHCurve self) -> Handle_GeomAdaptor_GHCurve"""
        return _GeomAdaptor.GeomAdaptor_GHCurve_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GeomAdaptor_GHCurve.Set = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHCurve_Set, None, GeomAdaptor_GHCurve)
GeomAdaptor_GHCurve.ChangeCurve = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHCurve_ChangeCurve, None, GeomAdaptor_GHCurve)
GeomAdaptor_GHCurve._kill_pointed = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHCurve__kill_pointed, None, GeomAdaptor_GHCurve)
GeomAdaptor_GHCurve.GetHandle = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHCurve_GetHandle, None, GeomAdaptor_GHCurve)
GeomAdaptor_GHCurve_swigregister = _GeomAdaptor.GeomAdaptor_GHCurve_swigregister
GeomAdaptor_GHCurve_swigregister(GeomAdaptor_GHCurve)

class Handle_GeomAdaptor_GHCurve(OCC.Adaptor3d.Handle_Adaptor3d_HCurve):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _GeomAdaptor.Handle_GeomAdaptor_GHCurve_swiginit(self, _GeomAdaptor.new_Handle_GeomAdaptor_GHCurve(*args))
    DownCast = staticmethod(_GeomAdaptor.Handle_GeomAdaptor_GHCurve_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_GeomAdaptor_GHCurve.Nullify = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHCurve_Nullify, None, Handle_GeomAdaptor_GHCurve)
Handle_GeomAdaptor_GHCurve.IsNull = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHCurve_IsNull, None, Handle_GeomAdaptor_GHCurve)
Handle_GeomAdaptor_GHCurve.GetObject = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHCurve_GetObject, None, Handle_GeomAdaptor_GHCurve)
Handle_GeomAdaptor_GHCurve._kill_pointed = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHCurve__kill_pointed, None, Handle_GeomAdaptor_GHCurve)
Handle_GeomAdaptor_GHCurve_swigregister = _GeomAdaptor.Handle_GeomAdaptor_GHCurve_swigregister
Handle_GeomAdaptor_GHCurve_swigregister(Handle_GeomAdaptor_GHCurve)

def Handle_GeomAdaptor_GHCurve_DownCast(AnObject):
    return _GeomAdaptor.Handle_GeomAdaptor_GHCurve_DownCast(AnObject)
Handle_GeomAdaptor_GHCurve_DownCast = _GeomAdaptor.Handle_GeomAdaptor_GHCurve_DownCast

class GeomAdaptor_GHSurface(OCC.Adaptor3d.Adaptor3d_HSurface):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param S:
        :type S: GeomAdaptor_Surface &
        :rtype: None

        """
        _GeomAdaptor.GeomAdaptor_GHSurface_swiginit(self, _GeomAdaptor.new_GeomAdaptor_GHSurface(*args))

    def Set(self, *args):
        """
        :param S:
        :type S: GeomAdaptor_Surface &
        :rtype: None

        """
        return _GeomAdaptor.GeomAdaptor_GHSurface_Set(self, *args)


    def ChangeSurface(self, *args):
        """
        :rtype: GeomAdaptor_Surface

        """
        return _GeomAdaptor.GeomAdaptor_GHSurface_ChangeSurface(self, *args)


    def _kill_pointed(self):
        """_kill_pointed(GeomAdaptor_GHSurface self)"""
        return _GeomAdaptor.GeomAdaptor_GHSurface__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(GeomAdaptor_GHSurface self) -> Handle_GeomAdaptor_GHSurface"""
        return _GeomAdaptor.GeomAdaptor_GHSurface_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GeomAdaptor_GHSurface.Set = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHSurface_Set, None, GeomAdaptor_GHSurface)
GeomAdaptor_GHSurface.ChangeSurface = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHSurface_ChangeSurface, None, GeomAdaptor_GHSurface)
GeomAdaptor_GHSurface._kill_pointed = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHSurface__kill_pointed, None, GeomAdaptor_GHSurface)
GeomAdaptor_GHSurface.GetHandle = new_instancemethod(_GeomAdaptor.GeomAdaptor_GHSurface_GetHandle, None, GeomAdaptor_GHSurface)
GeomAdaptor_GHSurface_swigregister = _GeomAdaptor.GeomAdaptor_GHSurface_swigregister
GeomAdaptor_GHSurface_swigregister(GeomAdaptor_GHSurface)

class Handle_GeomAdaptor_GHSurface(OCC.Adaptor3d.Handle_Adaptor3d_HSurface):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _GeomAdaptor.Handle_GeomAdaptor_GHSurface_swiginit(self, _GeomAdaptor.new_Handle_GeomAdaptor_GHSurface(*args))
    DownCast = staticmethod(_GeomAdaptor.Handle_GeomAdaptor_GHSurface_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_GeomAdaptor_GHSurface.Nullify = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHSurface_Nullify, None, Handle_GeomAdaptor_GHSurface)
Handle_GeomAdaptor_GHSurface.IsNull = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHSurface_IsNull, None, Handle_GeomAdaptor_GHSurface)
Handle_GeomAdaptor_GHSurface.GetObject = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHSurface_GetObject, None, Handle_GeomAdaptor_GHSurface)
Handle_GeomAdaptor_GHSurface._kill_pointed = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_GHSurface__kill_pointed, None, Handle_GeomAdaptor_GHSurface)
Handle_GeomAdaptor_GHSurface_swigregister = _GeomAdaptor.Handle_GeomAdaptor_GHSurface_swigregister
Handle_GeomAdaptor_GHSurface_swigregister(Handle_GeomAdaptor_GHSurface)

def Handle_GeomAdaptor_GHSurface_DownCast(AnObject):
    return _GeomAdaptor.Handle_GeomAdaptor_GHSurface_DownCast(AnObject)
Handle_GeomAdaptor_GHSurface_DownCast = _GeomAdaptor.Handle_GeomAdaptor_GHSurface_DownCast

class GeomAdaptor_Surface(OCC.Adaptor3d.Adaptor3d_Surface):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param S:
        :type S: Handle_Geom_Surface &
        :rtype: None

        * ConstructionError is raised if UFirst>ULast or VFirst>VLast

        :param S:
        :type S: Handle_Geom_Surface &
        :param UFirst:
        :type UFirst: float
        :param ULast:
        :type ULast: float
        :param VFirst:
        :type VFirst: float
        :param VLast:
        :type VLast: float
        :param TolU: default value is 0.0
        :type TolU: float
        :param TolV: default value is 0.0
        :type TolV: float
        :rtype: None

        """
        _GeomAdaptor.GeomAdaptor_Surface_swiginit(self, _GeomAdaptor.new_GeomAdaptor_Surface(*args))

    def Load(self, *args):
        """
        :param S:
        :type S: Handle_Geom_Surface &
        :rtype: None

        * ConstructionError is raised if UFirst>ULast or VFirst>VLast

        :param S:
        :type S: Handle_Geom_Surface &
        :param UFirst:
        :type UFirst: float
        :param ULast:
        :type ULast: float
        :param VFirst:
        :type VFirst: float
        :param VLast:
        :type VLast: float
        :param TolU: default value is 0.0
        :type TolU: float
        :param TolV: default value is 0.0
        :type TolV: float
        :rtype: None

        """
        return _GeomAdaptor.GeomAdaptor_Surface_Load(self, *args)


    def Surface(self, *args):
        """
        :rtype: Handle_Geom_Surface

        """
        return _GeomAdaptor.GeomAdaptor_Surface_Surface(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GeomAdaptor_Surface.Load = new_instancemethod(_GeomAdaptor.GeomAdaptor_Surface_Load, None, GeomAdaptor_Surface)
GeomAdaptor_Surface.Surface = new_instancemethod(_GeomAdaptor.GeomAdaptor_Surface_Surface, None, GeomAdaptor_Surface)
GeomAdaptor_Surface._kill_pointed = new_instancemethod(_GeomAdaptor.GeomAdaptor_Surface__kill_pointed, None, GeomAdaptor_Surface)
GeomAdaptor_Surface_swigregister = _GeomAdaptor.GeomAdaptor_Surface_swigregister
GeomAdaptor_Surface_swigregister(GeomAdaptor_Surface)

class GeomAdaptor_HCurve(GeomAdaptor_GHCurve):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param AS:
        :type AS: GeomAdaptor_Curve &
        :rtype: None

        :param S:
        :type S: Handle_Geom_Curve &
        :rtype: None

        * ConstructionError is raised if UFirst>ULast or VFirst>VLast

        :param S:
        :type S: Handle_Geom_Curve &
        :param UFirst:
        :type UFirst: float
        :param ULast:
        :type ULast: float
        :rtype: None

        """
        _GeomAdaptor.GeomAdaptor_HCurve_swiginit(self, _GeomAdaptor.new_GeomAdaptor_HCurve(*args))

    def _kill_pointed(self):
        """_kill_pointed(GeomAdaptor_HCurve self)"""
        return _GeomAdaptor.GeomAdaptor_HCurve__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(GeomAdaptor_HCurve self) -> Handle_GeomAdaptor_HCurve"""
        return _GeomAdaptor.GeomAdaptor_HCurve_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GeomAdaptor_HCurve._kill_pointed = new_instancemethod(_GeomAdaptor.GeomAdaptor_HCurve__kill_pointed, None, GeomAdaptor_HCurve)
GeomAdaptor_HCurve.GetHandle = new_instancemethod(_GeomAdaptor.GeomAdaptor_HCurve_GetHandle, None, GeomAdaptor_HCurve)
GeomAdaptor_HCurve_swigregister = _GeomAdaptor.GeomAdaptor_HCurve_swigregister
GeomAdaptor_HCurve_swigregister(GeomAdaptor_HCurve)

class Handle_GeomAdaptor_HCurve(Handle_GeomAdaptor_GHCurve):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _GeomAdaptor.Handle_GeomAdaptor_HCurve_swiginit(self, _GeomAdaptor.new_Handle_GeomAdaptor_HCurve(*args))
    DownCast = staticmethod(_GeomAdaptor.Handle_GeomAdaptor_HCurve_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_GeomAdaptor_HCurve.Nullify = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HCurve_Nullify, None, Handle_GeomAdaptor_HCurve)
Handle_GeomAdaptor_HCurve.IsNull = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HCurve_IsNull, None, Handle_GeomAdaptor_HCurve)
Handle_GeomAdaptor_HCurve.GetObject = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HCurve_GetObject, None, Handle_GeomAdaptor_HCurve)
Handle_GeomAdaptor_HCurve._kill_pointed = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HCurve__kill_pointed, None, Handle_GeomAdaptor_HCurve)
Handle_GeomAdaptor_HCurve_swigregister = _GeomAdaptor.Handle_GeomAdaptor_HCurve_swigregister
Handle_GeomAdaptor_HCurve_swigregister(Handle_GeomAdaptor_HCurve)

def Handle_GeomAdaptor_HCurve_DownCast(AnObject):
    return _GeomAdaptor.Handle_GeomAdaptor_HCurve_DownCast(AnObject)
Handle_GeomAdaptor_HCurve_DownCast = _GeomAdaptor.Handle_GeomAdaptor_HCurve_DownCast

class GeomAdaptor_HSurface(GeomAdaptor_GHSurface):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param AS:
        :type AS: GeomAdaptor_Surface &
        :rtype: None

        :param S:
        :type S: Handle_Geom_Surface &
        :rtype: None

        * ConstructionError is raised if UFirst>ULast or VFirst>VLast

        :param S:
        :type S: Handle_Geom_Surface &
        :param UFirst:
        :type UFirst: float
        :param ULast:
        :type ULast: float
        :param VFirst:
        :type VFirst: float
        :param VLast:
        :type VLast: float
        :param TolU: default value is 0.0
        :type TolU: float
        :param TolV: default value is 0.0
        :type TolV: float
        :rtype: None

        """
        _GeomAdaptor.GeomAdaptor_HSurface_swiginit(self, _GeomAdaptor.new_GeomAdaptor_HSurface(*args))

    def _kill_pointed(self):
        """_kill_pointed(GeomAdaptor_HSurface self)"""
        return _GeomAdaptor.GeomAdaptor_HSurface__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(GeomAdaptor_HSurface self) -> Handle_GeomAdaptor_HSurface"""
        return _GeomAdaptor.GeomAdaptor_HSurface_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GeomAdaptor_HSurface._kill_pointed = new_instancemethod(_GeomAdaptor.GeomAdaptor_HSurface__kill_pointed, None, GeomAdaptor_HSurface)
GeomAdaptor_HSurface.GetHandle = new_instancemethod(_GeomAdaptor.GeomAdaptor_HSurface_GetHandle, None, GeomAdaptor_HSurface)
GeomAdaptor_HSurface_swigregister = _GeomAdaptor.GeomAdaptor_HSurface_swigregister
GeomAdaptor_HSurface_swigregister(GeomAdaptor_HSurface)

class Handle_GeomAdaptor_HSurface(Handle_GeomAdaptor_GHSurface):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _GeomAdaptor.Handle_GeomAdaptor_HSurface_swiginit(self, _GeomAdaptor.new_Handle_GeomAdaptor_HSurface(*args))
    DownCast = staticmethod(_GeomAdaptor.Handle_GeomAdaptor_HSurface_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_GeomAdaptor_HSurface.Nullify = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HSurface_Nullify, None, Handle_GeomAdaptor_HSurface)
Handle_GeomAdaptor_HSurface.IsNull = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HSurface_IsNull, None, Handle_GeomAdaptor_HSurface)
Handle_GeomAdaptor_HSurface.GetObject = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HSurface_GetObject, None, Handle_GeomAdaptor_HSurface)
Handle_GeomAdaptor_HSurface._kill_pointed = new_instancemethod(_GeomAdaptor.Handle_GeomAdaptor_HSurface__kill_pointed, None, Handle_GeomAdaptor_HSurface)
Handle_GeomAdaptor_HSurface_swigregister = _GeomAdaptor.Handle_GeomAdaptor_HSurface_swigregister
Handle_GeomAdaptor_HSurface_swigregister(Handle_GeomAdaptor_HSurface)

def Handle_GeomAdaptor_HSurface_DownCast(AnObject):
    return _GeomAdaptor.Handle_GeomAdaptor_HSurface_DownCast(AnObject)
Handle_GeomAdaptor_HSurface_DownCast = _GeomAdaptor.Handle_GeomAdaptor_HSurface_DownCast



