# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _IntStart.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_IntStart', [dirname(__file__)])
        except ImportError:
            import _IntStart
            return _IntStart
        if fp is not None:
            try:
                _mod = imp.load_module('_IntStart', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _IntStart = swig_import_helper()
    del swig_import_helper
else:
    import _IntStart
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _IntStart.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_IntStart.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_IntStart.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_IntStart.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_IntStart.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_IntStart.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_IntStart.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_IntStart.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_IntStart.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_IntStart.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_IntStart.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_IntStart.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_IntStart.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_IntStart.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_IntStart.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_IntStart.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_IntStart.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _IntStart.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import OCC.MMgt
import OCC.Standard
import OCC.gp
import OCC.TopAbs
class IntStart_SITopolTool(OCC.MMgt.MMgt_TShared):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def Classify(self, *args):
        """
        :param P:
        :type P: gp_Pnt2d
        :param Tol:
        :type Tol: float
        :rtype: TopAbs_State

        """
        return _IntStart.IntStart_SITopolTool_Classify(self, *args)


    def _kill_pointed(self):
        """_kill_pointed(IntStart_SITopolTool self)"""
        return _IntStart.IntStart_SITopolTool__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(IntStart_SITopolTool self) -> Handle_IntStart_SITopolTool"""
        return _IntStart.IntStart_SITopolTool_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


IntStart_SITopolTool.Classify = new_instancemethod(_IntStart.IntStart_SITopolTool_Classify, None, IntStart_SITopolTool)
IntStart_SITopolTool._kill_pointed = new_instancemethod(_IntStart.IntStart_SITopolTool__kill_pointed, None, IntStart_SITopolTool)
IntStart_SITopolTool.GetHandle = new_instancemethod(_IntStart.IntStart_SITopolTool_GetHandle, None, IntStart_SITopolTool)
IntStart_SITopolTool_swigregister = _IntStart.IntStart_SITopolTool_swigregister
IntStart_SITopolTool_swigregister(IntStart_SITopolTool)

class Handle_IntStart_SITopolTool(OCC.MMgt.Handle_MMgt_TShared):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _IntStart.Handle_IntStart_SITopolTool_swiginit(self, _IntStart.new_Handle_IntStart_SITopolTool(*args))
    DownCast = staticmethod(_IntStart.Handle_IntStart_SITopolTool_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_IntStart_SITopolTool.Nullify = new_instancemethod(_IntStart.Handle_IntStart_SITopolTool_Nullify, None, Handle_IntStart_SITopolTool)
Handle_IntStart_SITopolTool.IsNull = new_instancemethod(_IntStart.Handle_IntStart_SITopolTool_IsNull, None, Handle_IntStart_SITopolTool)
Handle_IntStart_SITopolTool.GetObject = new_instancemethod(_IntStart.Handle_IntStart_SITopolTool_GetObject, None, Handle_IntStart_SITopolTool)
Handle_IntStart_SITopolTool._kill_pointed = new_instancemethod(_IntStart.Handle_IntStart_SITopolTool__kill_pointed, None, Handle_IntStart_SITopolTool)
Handle_IntStart_SITopolTool_swigregister = _IntStart.Handle_IntStart_SITopolTool_swigregister
Handle_IntStart_SITopolTool_swigregister(Handle_IntStart_SITopolTool)

def Handle_IntStart_SITopolTool_DownCast(AnObject):
    return _IntStart.Handle_IntStart_SITopolTool_DownCast(AnObject)
Handle_IntStart_SITopolTool_DownCast = _IntStart.Handle_IntStart_SITopolTool_DownCast



