# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _ShapeCustom.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ShapeCustom', [dirname(__file__)])
        except ImportError:
            import _ShapeCustom
            return _ShapeCustom
        if fp is not None:
            try:
                _mod = imp.load_module('_ShapeCustom', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ShapeCustom = swig_import_helper()
    del swig_import_helper
else:
    import _ShapeCustom
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ShapeCustom.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_ShapeCustom.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_ShapeCustom.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_ShapeCustom.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_ShapeCustom.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_ShapeCustom.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_ShapeCustom.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_ShapeCustom.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_ShapeCustom.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_ShapeCustom.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_ShapeCustom.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_ShapeCustom.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_ShapeCustom.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_ShapeCustom.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_ShapeCustom.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_ShapeCustom.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_ShapeCustom.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _ShapeCustom.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import OCC.TopoDS
import OCC.MMgt
import OCC.Standard
import OCC.TCollection
import OCC.TopLoc
import OCC.gp
import OCC.TopAbs
import OCC.BRepTools
import OCC.Bnd
import OCC.TColStd
import OCC.TopTools
import OCC.Message
import OCC.BRep
import OCC.Geom
import OCC.GeomAbs
import OCC.TColgp
import OCC.Poly
import OCC.NCollection
import OCC.TShort
import OCC.Geom2d
class shapecustom(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def ApplyModifier(*args):
        """
        * Applies modifier to shape and checks sharing in the case assemblies.

        :param S:
        :type S: TopoDS_Shape &
        :param M:
        :type M: Handle_BRepTools_Modification &
        :param context:
        :type context: TopTools_DataMapOfShapeShape &
        :param MD:
        :type MD: BRepTools_Modifier &
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_ApplyModifier(*args)

    ApplyModifier = staticmethod(ApplyModifier)

    def DirectFaces(*args):
        """
        * Returns a new shape without indirect surfaces.

        :param S:
        :type S: TopoDS_Shape &
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_DirectFaces(*args)

    DirectFaces = staticmethod(DirectFaces)

    def ScaleShape(*args):
        """
        * Returns a new shape which is scaled original

        :param S:
        :type S: TopoDS_Shape &
        :param scale:
        :type scale: float
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_ScaleShape(*args)

    ScaleShape = staticmethod(ScaleShape)

    def BSplineRestriction(*args):
        """
        * Returns a new shape with all surfaces, curves and pcurves which type is BSpline/Bezier or based on them converted having Degree less than <MaxDegree> or number of spans less than <NbMaxSegment> in dependence on parameter priority <Degree>. <GmaxDegree> and <GMaxSegments> are maximum possible degree and number of spans correspondingly. These values will be used in those cases when approximation with specified parameters is impossible and one of GmaxDegree or GMaxSegments is selected in dependence on priority. Note that even if approximation is impossible with <GMaxDegree> then number of spans can exceed specified <GMaxSegment> <Rational> specifies if to convert Rational BSpline/Bezier into polynomial B-Spline. If flags ConvOffSurf,ConvOffCurve3d,ConvOffCurve2d are Standard_True there are means that Offset surfaces , Offset curves 3d and Offset curves 2d are converted to BSPline correspondingly.

        :param S:
        :type S: TopoDS_Shape &
        :param Tol3d:
        :type Tol3d: float
        :param Tol2d:
        :type Tol2d: float
        :param MaxDegree:
        :type MaxDegree: int
        :param MaxNbSegment:
        :type MaxNbSegment: int
        :param Continuity3d:
        :type Continuity3d: GeomAbs_Shape
        :param Continuity2d:
        :type Continuity2d: GeomAbs_Shape
        :param Degree:
        :type Degree: bool
        :param Rational:
        :type Rational: bool
        :param aParameters:
        :type aParameters: Handle_ShapeCustom_RestrictionParameters &
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_BSplineRestriction(*args)

    BSplineRestriction = staticmethod(BSplineRestriction)

    def ConvertToRevolution(*args):
        """
        * Returns a new shape with all elementary periodic surfaces converted to Geom_SurfaceOfRevolution

        :param S:
        :type S: TopoDS_Shape &
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_ConvertToRevolution(*args)

    ConvertToRevolution = staticmethod(ConvertToRevolution)

    def SweptToElementary(*args):
        """
        * Returns a new shape with all surfaces of revolution and linear extrusion convert to elementary periodic surfaces

        :param S:
        :type S: TopoDS_Shape &
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_SweptToElementary(*args)

    SweptToElementary = staticmethod(SweptToElementary)

    def ConvertToBSpline(*args):
        """
        * Returns a new shape with all surfaces of linear extrusion, revolution, offset, and planar surfaces converted according to flags to Geom_BSplineSurface (with same parameterisation).

        :param S:
        :type S: TopoDS_Shape &
        :param extrMode:
        :type extrMode: bool
        :param revolMode:
        :type revolMode: bool
        :param offsetMode:
        :type offsetMode: bool
        :param planeMode: default value is Standard_False
        :type planeMode: bool
        :rtype: TopoDS_Shape

        """
        return _ShapeCustom.shapecustom_ConvertToBSpline(*args)

    ConvertToBSpline = staticmethod(ConvertToBSpline)

    def __init__(self):
        _ShapeCustom.shapecustom_swiginit(self, _ShapeCustom.new_shapecustom())

    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


shapecustom._kill_pointed = new_instancemethod(_ShapeCustom.shapecustom__kill_pointed, None, shapecustom)
shapecustom_swigregister = _ShapeCustom.shapecustom_swigregister
shapecustom_swigregister(shapecustom)

def shapecustom_ApplyModifier(*args):
    """
    * Applies modifier to shape and checks sharing in the case assemblies.

    :param S:
    :type S: TopoDS_Shape &
    :param M:
    :type M: Handle_BRepTools_Modification &
    :param context:
    :type context: TopTools_DataMapOfShapeShape &
    :param MD:
    :type MD: BRepTools_Modifier &
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_ApplyModifier(*args)

def shapecustom_DirectFaces(*args):
    """
    * Returns a new shape without indirect surfaces.

    :param S:
    :type S: TopoDS_Shape &
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_DirectFaces(*args)

def shapecustom_ScaleShape(*args):
    """
    * Returns a new shape which is scaled original

    :param S:
    :type S: TopoDS_Shape &
    :param scale:
    :type scale: float
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_ScaleShape(*args)

def shapecustom_BSplineRestriction(*args):
    """
    * Returns a new shape with all surfaces, curves and pcurves which type is BSpline/Bezier or based on them converted having Degree less than <MaxDegree> or number of spans less than <NbMaxSegment> in dependence on parameter priority <Degree>. <GmaxDegree> and <GMaxSegments> are maximum possible degree and number of spans correspondingly. These values will be used in those cases when approximation with specified parameters is impossible and one of GmaxDegree or GMaxSegments is selected in dependence on priority. Note that even if approximation is impossible with <GMaxDegree> then number of spans can exceed specified <GMaxSegment> <Rational> specifies if to convert Rational BSpline/Bezier into polynomial B-Spline. If flags ConvOffSurf,ConvOffCurve3d,ConvOffCurve2d are Standard_True there are means that Offset surfaces , Offset curves 3d and Offset curves 2d are converted to BSPline correspondingly.

    :param S:
    :type S: TopoDS_Shape &
    :param Tol3d:
    :type Tol3d: float
    :param Tol2d:
    :type Tol2d: float
    :param MaxDegree:
    :type MaxDegree: int
    :param MaxNbSegment:
    :type MaxNbSegment: int
    :param Continuity3d:
    :type Continuity3d: GeomAbs_Shape
    :param Continuity2d:
    :type Continuity2d: GeomAbs_Shape
    :param Degree:
    :type Degree: bool
    :param Rational:
    :type Rational: bool
    :param aParameters:
    :type aParameters: Handle_ShapeCustom_RestrictionParameters &
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_BSplineRestriction(*args)

def shapecustom_ConvertToRevolution(*args):
    """
    * Returns a new shape with all elementary periodic surfaces converted to Geom_SurfaceOfRevolution

    :param S:
    :type S: TopoDS_Shape &
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_ConvertToRevolution(*args)

def shapecustom_SweptToElementary(*args):
    """
    * Returns a new shape with all surfaces of revolution and linear extrusion convert to elementary periodic surfaces

    :param S:
    :type S: TopoDS_Shape &
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_SweptToElementary(*args)

def shapecustom_ConvertToBSpline(*args):
    """
    * Returns a new shape with all surfaces of linear extrusion, revolution, offset, and planar surfaces converted according to flags to Geom_BSplineSurface (with same parameterisation).

    :param S:
    :type S: TopoDS_Shape &
    :param extrMode:
    :type extrMode: bool
    :param revolMode:
    :type revolMode: bool
    :param offsetMode:
    :type offsetMode: bool
    :param planeMode: default value is Standard_False
    :type planeMode: bool
    :rtype: TopoDS_Shape

    """
    return _ShapeCustom.shapecustom_ConvertToBSpline(*args)

class ShapeCustom_ConvertToBSpline(OCC.BRepTools.BRepTools_Modification):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _ShapeCustom.ShapeCustom_ConvertToBSpline_swiginit(self, _ShapeCustom.new_ShapeCustom_ConvertToBSpline(*args))

    def SetExtrusionMode(self, *args):
        """
        * Sets mode for convertion of Surfaces of Linear extrusion.

        :param extrMode:
        :type extrMode: bool
        :rtype: None

        """
        return _ShapeCustom.ShapeCustom_ConvertToBSpline_SetExtrusionMode(self, *args)


    def SetRevolutionMode(self, *args):
        """
        * Sets mode for convertion of Surfaces of Revolution.

        :param revolMode:
        :type revolMode: bool
        :rtype: None

        """
        return _ShapeCustom.ShapeCustom_ConvertToBSpline_SetRevolutionMode(self, *args)


    def SetOffsetMode(self, *args):
        """
        * Sets mode for convertion of Offset surfaces.

        :param offsetMode:
        :type offsetMode: bool
        :rtype: None

        """
        return _ShapeCustom.ShapeCustom_ConvertToBSpline_SetOffsetMode(self, *args)


    def SetPlaneMode(self, *args):
        """
        * Sets mode for convertion of Plane surfaces.

        :param planeMode:
        :type planeMode: bool
        :rtype: None

        """
        return _ShapeCustom.ShapeCustom_ConvertToBSpline_SetPlaneMode(self, *args)


    def _kill_pointed(self):
        """_kill_pointed(ShapeCustom_ConvertToBSpline self)"""
        return _ShapeCustom.ShapeCustom_ConvertToBSpline__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(ShapeCustom_ConvertToBSpline self) -> Handle_ShapeCustom_ConvertToBSpline"""
        return _ShapeCustom.ShapeCustom_ConvertToBSpline_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_ConvertToBSpline.SetExtrusionMode = new_instancemethod(_ShapeCustom.ShapeCustom_ConvertToBSpline_SetExtrusionMode, None, ShapeCustom_ConvertToBSpline)
ShapeCustom_ConvertToBSpline.SetRevolutionMode = new_instancemethod(_ShapeCustom.ShapeCustom_ConvertToBSpline_SetRevolutionMode, None, ShapeCustom_ConvertToBSpline)
ShapeCustom_ConvertToBSpline.SetOffsetMode = new_instancemethod(_ShapeCustom.ShapeCustom_ConvertToBSpline_SetOffsetMode, None, ShapeCustom_ConvertToBSpline)
ShapeCustom_ConvertToBSpline.SetPlaneMode = new_instancemethod(_ShapeCustom.ShapeCustom_ConvertToBSpline_SetPlaneMode, None, ShapeCustom_ConvertToBSpline)
ShapeCustom_ConvertToBSpline._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_ConvertToBSpline__kill_pointed, None, ShapeCustom_ConvertToBSpline)
ShapeCustom_ConvertToBSpline.GetHandle = new_instancemethod(_ShapeCustom.ShapeCustom_ConvertToBSpline_GetHandle, None, ShapeCustom_ConvertToBSpline)
ShapeCustom_ConvertToBSpline_swigregister = _ShapeCustom.ShapeCustom_ConvertToBSpline_swigregister
ShapeCustom_ConvertToBSpline_swigregister(ShapeCustom_ConvertToBSpline)

class Handle_ShapeCustom_ConvertToBSpline(OCC.BRepTools.Handle_BRepTools_Modification):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_swiginit(self, _ShapeCustom.new_Handle_ShapeCustom_ConvertToBSpline(*args))
    DownCast = staticmethod(_ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_ShapeCustom_ConvertToBSpline.Nullify = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_Nullify, None, Handle_ShapeCustom_ConvertToBSpline)
Handle_ShapeCustom_ConvertToBSpline.IsNull = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_IsNull, None, Handle_ShapeCustom_ConvertToBSpline)
Handle_ShapeCustom_ConvertToBSpline.GetObject = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_GetObject, None, Handle_ShapeCustom_ConvertToBSpline)
Handle_ShapeCustom_ConvertToBSpline._kill_pointed = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_ConvertToBSpline__kill_pointed, None, Handle_ShapeCustom_ConvertToBSpline)
Handle_ShapeCustom_ConvertToBSpline_swigregister = _ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_swigregister
Handle_ShapeCustom_ConvertToBSpline_swigregister(Handle_ShapeCustom_ConvertToBSpline)

def Handle_ShapeCustom_ConvertToBSpline_DownCast(AnObject):
    return _ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_DownCast(AnObject)
Handle_ShapeCustom_ConvertToBSpline_DownCast = _ShapeCustom.Handle_ShapeCustom_ConvertToBSpline_DownCast

class ShapeCustom_Curve(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param C:
        :type C: Handle_Geom_Curve &
        :rtype: None

        """
        _ShapeCustom.ShapeCustom_Curve_swiginit(self, _ShapeCustom.new_ShapeCustom_Curve(*args))

    def Init(self, *args):
        """
        :param C:
        :type C: Handle_Geom_Curve &
        :rtype: None

        """
        return _ShapeCustom.ShapeCustom_Curve_Init(self, *args)


    def ConvertToPeriodic(self, *args):
        """
        * Tries to convert the Curve to the Periodic form Returns the resulting curve Works only if the Curve is BSpline and is closed with Precision::Confusion() Else, or in case of failure, returns a Null Handle

        :param substitute:
        :type substitute: bool
        :param preci: default value is -1
        :type preci: float
        :rtype: Handle_Geom_Curve

        """
        return _ShapeCustom.ShapeCustom_Curve_ConvertToPeriodic(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_Curve.Init = new_instancemethod(_ShapeCustom.ShapeCustom_Curve_Init, None, ShapeCustom_Curve)
ShapeCustom_Curve.ConvertToPeriodic = new_instancemethod(_ShapeCustom.ShapeCustom_Curve_ConvertToPeriodic, None, ShapeCustom_Curve)
ShapeCustom_Curve._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_Curve__kill_pointed, None, ShapeCustom_Curve)
ShapeCustom_Curve_swigregister = _ShapeCustom.ShapeCustom_Curve_swigregister
ShapeCustom_Curve_swigregister(ShapeCustom_Curve)

class ShapeCustom_Curve2d(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def IsLinear(*args):
        """
        * Check if poleses is in the plane with given precision Returns false if no.

        :param thePoles:
        :type thePoles: TColgp_Array1OfPnt2d
        :param theTolerance:
        :type theTolerance: float
        :param theDeviation:
        :type theDeviation: float &
        :rtype: bool

        """
        return _ShapeCustom.ShapeCustom_Curve2d_IsLinear(*args)

    IsLinear = staticmethod(IsLinear)

    def ConvertToLine2d(*args):
        """
        * Try to convert BSpline2d or Bezier2d to line 2d only if it is linear. Recalculate first and last parameters. Returns line2d or null curve2d.

        :param theCurve:
        :type theCurve: Handle_Geom2d_Curve &
        :param theFirstIn:
        :type theFirstIn: float
        :param theLastIn:
        :type theLastIn: float
        :param theTolerance:
        :type theTolerance: float
        :param theNewFirst:
        :type theNewFirst: float &
        :param theNewLast:
        :type theNewLast: float &
        :param theDeviation:
        :type theDeviation: float &
        :rtype: Handle_Geom2d_Line

        """
        return _ShapeCustom.ShapeCustom_Curve2d_ConvertToLine2d(*args)

    ConvertToLine2d = staticmethod(ConvertToLine2d)

    def SimplifyBSpline2d(*args):
        """
        * Try to remove knots from bspline where local derivatives are the same. Remove knots with given precision. Returns false if Bsplien was not modified

        :param theBSpline2d:
        :type theBSpline2d: Handle_Geom2d_BSplineCurve &
        :param theTolerance:
        :type theTolerance: float
        :rtype: bool

        """
        return _ShapeCustom.ShapeCustom_Curve2d_SimplifyBSpline2d(*args)

    SimplifyBSpline2d = staticmethod(SimplifyBSpline2d)

    def __init__(self):
        _ShapeCustom.ShapeCustom_Curve2d_swiginit(self, _ShapeCustom.new_ShapeCustom_Curve2d())

    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_Curve2d._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_Curve2d__kill_pointed, None, ShapeCustom_Curve2d)
ShapeCustom_Curve2d_swigregister = _ShapeCustom.ShapeCustom_Curve2d_swigregister
ShapeCustom_Curve2d_swigregister(ShapeCustom_Curve2d)

def ShapeCustom_Curve2d_IsLinear(*args):
    """
    * Check if poleses is in the plane with given precision Returns false if no.

    :param thePoles:
    :type thePoles: TColgp_Array1OfPnt2d
    :param theTolerance:
    :type theTolerance: float
    :param theDeviation:
    :type theDeviation: float &
    :rtype: bool

    """
    return _ShapeCustom.ShapeCustom_Curve2d_IsLinear(*args)

def ShapeCustom_Curve2d_ConvertToLine2d(*args):
    """
    * Try to convert BSpline2d or Bezier2d to line 2d only if it is linear. Recalculate first and last parameters. Returns line2d or null curve2d.

    :param theCurve:
    :type theCurve: Handle_Geom2d_Curve &
    :param theFirstIn:
    :type theFirstIn: float
    :param theLastIn:
    :type theLastIn: float
    :param theTolerance:
    :type theTolerance: float
    :param theNewFirst:
    :type theNewFirst: float &
    :param theNewLast:
    :type theNewLast: float &
    :param theDeviation:
    :type theDeviation: float &
    :rtype: Handle_Geom2d_Line

    """
    return _ShapeCustom.ShapeCustom_Curve2d_ConvertToLine2d(*args)

def ShapeCustom_Curve2d_SimplifyBSpline2d(*args):
    """
    * Try to remove knots from bspline where local derivatives are the same. Remove knots with given precision. Returns false if Bsplien was not modified

    :param theBSpline2d:
    :type theBSpline2d: Handle_Geom2d_BSplineCurve &
    :param theTolerance:
    :type theTolerance: float
    :rtype: bool

    """
    return _ShapeCustom.ShapeCustom_Curve2d_SimplifyBSpline2d(*args)

class ShapeCustom_DirectModification(OCC.BRepTools.BRepTools_Modification):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _ShapeCustom.ShapeCustom_DirectModification_swiginit(self, _ShapeCustom.new_ShapeCustom_DirectModification(*args))

    def _kill_pointed(self):
        """_kill_pointed(ShapeCustom_DirectModification self)"""
        return _ShapeCustom.ShapeCustom_DirectModification__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(ShapeCustom_DirectModification self) -> Handle_ShapeCustom_DirectModification"""
        return _ShapeCustom.ShapeCustom_DirectModification_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_DirectModification._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_DirectModification__kill_pointed, None, ShapeCustom_DirectModification)
ShapeCustom_DirectModification.GetHandle = new_instancemethod(_ShapeCustom.ShapeCustom_DirectModification_GetHandle, None, ShapeCustom_DirectModification)
ShapeCustom_DirectModification_swigregister = _ShapeCustom.ShapeCustom_DirectModification_swigregister
ShapeCustom_DirectModification_swigregister(ShapeCustom_DirectModification)

class Handle_ShapeCustom_DirectModification(OCC.BRepTools.Handle_BRepTools_Modification):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ShapeCustom.Handle_ShapeCustom_DirectModification_swiginit(self, _ShapeCustom.new_Handle_ShapeCustom_DirectModification(*args))
    DownCast = staticmethod(_ShapeCustom.Handle_ShapeCustom_DirectModification_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_ShapeCustom_DirectModification.Nullify = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_DirectModification_Nullify, None, Handle_ShapeCustom_DirectModification)
Handle_ShapeCustom_DirectModification.IsNull = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_DirectModification_IsNull, None, Handle_ShapeCustom_DirectModification)
Handle_ShapeCustom_DirectModification.GetObject = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_DirectModification_GetObject, None, Handle_ShapeCustom_DirectModification)
Handle_ShapeCustom_DirectModification._kill_pointed = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_DirectModification__kill_pointed, None, Handle_ShapeCustom_DirectModification)
Handle_ShapeCustom_DirectModification_swigregister = _ShapeCustom.Handle_ShapeCustom_DirectModification_swigregister
Handle_ShapeCustom_DirectModification_swigregister(Handle_ShapeCustom_DirectModification)

def Handle_ShapeCustom_DirectModification_DownCast(AnObject):
    return _ShapeCustom.Handle_ShapeCustom_DirectModification_DownCast(AnObject)
Handle_ShapeCustom_DirectModification_DownCast = _ShapeCustom.Handle_ShapeCustom_DirectModification_DownCast

class ShapeCustom_RestrictionParameters(OCC.MMgt.MMgt_TShared):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Sets default parameters.

        :rtype: None

        """
        _ShapeCustom.ShapeCustom_RestrictionParameters_swiginit(self, _ShapeCustom.new_ShapeCustom_RestrictionParameters(*args))

    def GetGMaxDegree(self):
        """GetGMaxDegree(ShapeCustom_RestrictionParameters self) -> Standard_Integer"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetGMaxDegree(self)


    def SetGMaxDegree(self, value):
        """SetGMaxDegree(ShapeCustom_RestrictionParameters self, Standard_Integer value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetGMaxDegree(self, value)


    def GetGMaxSeg(self):
        """GetGMaxSeg(ShapeCustom_RestrictionParameters self) -> Standard_Integer"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetGMaxSeg(self)


    def SetGMaxSeg(self, value):
        """SetGMaxSeg(ShapeCustom_RestrictionParameters self, Standard_Integer value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetGMaxSeg(self, value)


    def GetConvertPlane(self):
        """GetConvertPlane(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertPlane(self)


    def SetConvertPlane(self, value):
        """SetConvertPlane(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertPlane(self, value)


    def GetConvertBezierSurf(self):
        """GetConvertBezierSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertBezierSurf(self)


    def SetConvertBezierSurf(self, value):
        """SetConvertBezierSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertBezierSurf(self, value)


    def GetConvertRevolutionSurf(self):
        """GetConvertRevolutionSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertRevolutionSurf(self)


    def SetConvertRevolutionSurf(self, value):
        """SetConvertRevolutionSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertRevolutionSurf(self, value)


    def GetConvertExtrusionSurf(self):
        """GetConvertExtrusionSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertExtrusionSurf(self)


    def SetConvertExtrusionSurf(self, value):
        """SetConvertExtrusionSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertExtrusionSurf(self, value)


    def GetConvertOffsetSurf(self):
        """GetConvertOffsetSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertOffsetSurf(self)


    def SetConvertOffsetSurf(self, value):
        """SetConvertOffsetSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertOffsetSurf(self, value)


    def GetConvertCylindricalSurf(self):
        """GetConvertCylindricalSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertCylindricalSurf(self)


    def SetConvertCylindricalSurf(self, value):
        """SetConvertCylindricalSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertCylindricalSurf(self, value)


    def GetConvertConicalSurf(self):
        """GetConvertConicalSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertConicalSurf(self)


    def SetConvertConicalSurf(self, value):
        """SetConvertConicalSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertConicalSurf(self, value)


    def GetConvertToroidalSurf(self):
        """GetConvertToroidalSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertToroidalSurf(self)


    def SetConvertToroidalSurf(self, value):
        """SetConvertToroidalSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertToroidalSurf(self, value)


    def GetConvertSphericalSurf(self):
        """GetConvertSphericalSurf(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertSphericalSurf(self)


    def SetConvertSphericalSurf(self, value):
        """SetConvertSphericalSurf(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertSphericalSurf(self, value)


    def GetSegmentSurfaceMode(self):
        """GetSegmentSurfaceMode(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetSegmentSurfaceMode(self)


    def SetSegmentSurfaceMode(self, value):
        """SetSegmentSurfaceMode(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetSegmentSurfaceMode(self, value)


    def GetConvertCurve3d(self):
        """GetConvertCurve3d(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertCurve3d(self)


    def SetConvertCurve3d(self, value):
        """SetConvertCurve3d(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertCurve3d(self, value)


    def GetConvertOffsetCurv3d(self):
        """GetConvertOffsetCurv3d(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertOffsetCurv3d(self)


    def SetConvertOffsetCurv3d(self, value):
        """SetConvertOffsetCurv3d(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertOffsetCurv3d(self, value)


    def GetConvertCurve2d(self):
        """GetConvertCurve2d(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertCurve2d(self)


    def SetConvertCurve2d(self, value):
        """SetConvertCurve2d(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertCurve2d(self, value)


    def GetConvertOffsetCurv2d(self):
        """GetConvertOffsetCurv2d(ShapeCustom_RestrictionParameters self) -> Standard_Boolean"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertOffsetCurv2d(self)


    def SetConvertOffsetCurv2d(self, value):
        """SetConvertOffsetCurv2d(ShapeCustom_RestrictionParameters self, Standard_Boolean value)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertOffsetCurv2d(self, value)


    def _kill_pointed(self):
        """_kill_pointed(ShapeCustom_RestrictionParameters self)"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(ShapeCustom_RestrictionParameters self) -> Handle_ShapeCustom_RestrictionParameters"""
        return _ShapeCustom.ShapeCustom_RestrictionParameters_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_RestrictionParameters.GetGMaxDegree = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetGMaxDegree, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetGMaxDegree = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetGMaxDegree, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetGMaxSeg = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetGMaxSeg, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetGMaxSeg = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetGMaxSeg, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertPlane = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertPlane, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertPlane = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertPlane, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertBezierSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertBezierSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertBezierSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertBezierSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertRevolutionSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertRevolutionSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertRevolutionSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertRevolutionSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertExtrusionSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertExtrusionSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertExtrusionSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertExtrusionSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertOffsetSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertOffsetSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertOffsetSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertOffsetSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertCylindricalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertCylindricalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertCylindricalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertCylindricalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertConicalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertConicalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertConicalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertConicalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertToroidalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertToroidalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertToroidalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertToroidalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertSphericalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertSphericalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertSphericalSurf = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertSphericalSurf, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetSegmentSurfaceMode = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetSegmentSurfaceMode, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetSegmentSurfaceMode = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetSegmentSurfaceMode, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertCurve3d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertCurve3d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertCurve3d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertCurve3d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertOffsetCurv3d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertOffsetCurv3d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertOffsetCurv3d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertOffsetCurv3d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertCurve2d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertCurve2d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertCurve2d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertCurve2d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetConvertOffsetCurv2d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetConvertOffsetCurv2d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.SetConvertOffsetCurv2d = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_SetConvertOffsetCurv2d, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters__kill_pointed, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters.GetHandle = new_instancemethod(_ShapeCustom.ShapeCustom_RestrictionParameters_GetHandle, None, ShapeCustom_RestrictionParameters)
ShapeCustom_RestrictionParameters_swigregister = _ShapeCustom.ShapeCustom_RestrictionParameters_swigregister
ShapeCustom_RestrictionParameters_swigregister(ShapeCustom_RestrictionParameters)

class Handle_ShapeCustom_RestrictionParameters(OCC.MMgt.Handle_MMgt_TShared):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ShapeCustom.Handle_ShapeCustom_RestrictionParameters_swiginit(self, _ShapeCustom.new_Handle_ShapeCustom_RestrictionParameters(*args))
    DownCast = staticmethod(_ShapeCustom.Handle_ShapeCustom_RestrictionParameters_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_ShapeCustom_RestrictionParameters.Nullify = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_RestrictionParameters_Nullify, None, Handle_ShapeCustom_RestrictionParameters)
Handle_ShapeCustom_RestrictionParameters.IsNull = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_RestrictionParameters_IsNull, None, Handle_ShapeCustom_RestrictionParameters)
Handle_ShapeCustom_RestrictionParameters.GetObject = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_RestrictionParameters_GetObject, None, Handle_ShapeCustom_RestrictionParameters)
Handle_ShapeCustom_RestrictionParameters._kill_pointed = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_RestrictionParameters__kill_pointed, None, Handle_ShapeCustom_RestrictionParameters)
Handle_ShapeCustom_RestrictionParameters_swigregister = _ShapeCustom.Handle_ShapeCustom_RestrictionParameters_swigregister
Handle_ShapeCustom_RestrictionParameters_swigregister(Handle_ShapeCustom_RestrictionParameters)

def Handle_ShapeCustom_RestrictionParameters_DownCast(AnObject):
    return _ShapeCustom.Handle_ShapeCustom_RestrictionParameters_DownCast(AnObject)
Handle_ShapeCustom_RestrictionParameters_DownCast = _ShapeCustom.Handle_ShapeCustom_RestrictionParameters_DownCast

class ShapeCustom_Surface(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param S:
        :type S: Handle_Geom_Surface &
        :rtype: None

        """
        _ShapeCustom.ShapeCustom_Surface_swiginit(self, _ShapeCustom.new_ShapeCustom_Surface(*args))

    def Init(self, *args):
        """
        :param S:
        :type S: Handle_Geom_Surface &
        :rtype: None

        """
        return _ShapeCustom.ShapeCustom_Surface_Init(self, *args)


    def Gap(self, *args):
        """
        * Returns maximal deviation of converted surface from the original one computed by last call to ConvertToAnalytical

        :rtype: float

        """
        return _ShapeCustom.ShapeCustom_Surface_Gap(self, *args)


    def ConvertToAnalytical(self, *args):
        """
        * Tries to convert the Surface to an Analytic form Returns the result Works only if the Surface is BSpline or Bezier. Else, or in case of failure, returns a Null Handle  If <substitute> is True, the new surface replaces the actual one in <self>  It works by analysing the case which can apply, creating the corresponding analytic surface, then checking coincidence Warning: Parameter laws are not kept, hence PCurves should be redone

        :param tol:
        :type tol: float
        :param substitute:
        :type substitute: bool
        :rtype: Handle_Geom_Surface

        """
        return _ShapeCustom.ShapeCustom_Surface_ConvertToAnalytical(self, *args)


    def ConvertToPeriodic(self, *args):
        """
        * Tries to convert the Surface to the Periodic form Returns the resulting surface Works only if the Surface is BSpline and is closed with Precision::Confusion() Else, or in case of failure, returns a Null Handle

        :param substitute:
        :type substitute: bool
        :param preci: default value is -1
        :type preci: float
        :rtype: Handle_Geom_Surface

        """
        return _ShapeCustom.ShapeCustom_Surface_ConvertToPeriodic(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_Surface.Init = new_instancemethod(_ShapeCustom.ShapeCustom_Surface_Init, None, ShapeCustom_Surface)
ShapeCustom_Surface.Gap = new_instancemethod(_ShapeCustom.ShapeCustom_Surface_Gap, None, ShapeCustom_Surface)
ShapeCustom_Surface.ConvertToAnalytical = new_instancemethod(_ShapeCustom.ShapeCustom_Surface_ConvertToAnalytical, None, ShapeCustom_Surface)
ShapeCustom_Surface.ConvertToPeriodic = new_instancemethod(_ShapeCustom.ShapeCustom_Surface_ConvertToPeriodic, None, ShapeCustom_Surface)
ShapeCustom_Surface._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_Surface__kill_pointed, None, ShapeCustom_Surface)
ShapeCustom_Surface_swigregister = _ShapeCustom.ShapeCustom_Surface_swigregister
ShapeCustom_Surface_swigregister(ShapeCustom_Surface)

class ShapeCustom_TrsfModification(OCC.BRepTools.BRepTools_TrsfModification):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :param T:
        :type T: gp_Trsf
        :rtype: None

        """
        _ShapeCustom.ShapeCustom_TrsfModification_swiginit(self, _ShapeCustom.new_ShapeCustom_TrsfModification(*args))

    def _kill_pointed(self):
        """_kill_pointed(ShapeCustom_TrsfModification self)"""
        return _ShapeCustom.ShapeCustom_TrsfModification__kill_pointed(self)


    def GetHandle(self):
        """GetHandle(ShapeCustom_TrsfModification self) -> Handle_ShapeCustom_TrsfModification"""
        return _ShapeCustom.ShapeCustom_TrsfModification_GetHandle(self)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


ShapeCustom_TrsfModification._kill_pointed = new_instancemethod(_ShapeCustom.ShapeCustom_TrsfModification__kill_pointed, None, ShapeCustom_TrsfModification)
ShapeCustom_TrsfModification.GetHandle = new_instancemethod(_ShapeCustom.ShapeCustom_TrsfModification_GetHandle, None, ShapeCustom_TrsfModification)
ShapeCustom_TrsfModification_swigregister = _ShapeCustom.ShapeCustom_TrsfModification_swigregister
ShapeCustom_TrsfModification_swigregister(ShapeCustom_TrsfModification)

class Handle_ShapeCustom_TrsfModification(OCC.BRepTools.Handle_BRepTools_TrsfModification):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _ShapeCustom.Handle_ShapeCustom_TrsfModification_swiginit(self, _ShapeCustom.new_Handle_ShapeCustom_TrsfModification(*args))
    DownCast = staticmethod(_ShapeCustom.Handle_ShapeCustom_TrsfModification_DownCast)

    def __del__(self):
        try:
            self.thisown = False
            GarbageCollector.garbage.collect_object(self)
        except:
            pass


Handle_ShapeCustom_TrsfModification.Nullify = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_TrsfModification_Nullify, None, Handle_ShapeCustom_TrsfModification)
Handle_ShapeCustom_TrsfModification.IsNull = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_TrsfModification_IsNull, None, Handle_ShapeCustom_TrsfModification)
Handle_ShapeCustom_TrsfModification.GetObject = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_TrsfModification_GetObject, None, Handle_ShapeCustom_TrsfModification)
Handle_ShapeCustom_TrsfModification._kill_pointed = new_instancemethod(_ShapeCustom.Handle_ShapeCustom_TrsfModification__kill_pointed, None, Handle_ShapeCustom_TrsfModification)
Handle_ShapeCustom_TrsfModification_swigregister = _ShapeCustom.Handle_ShapeCustom_TrsfModification_swigregister
Handle_ShapeCustom_TrsfModification_swigregister(Handle_ShapeCustom_TrsfModification)

def Handle_ShapeCustom_TrsfModification_DownCast(AnObject):
    return _ShapeCustom.Handle_ShapeCustom_TrsfModification_DownCast(AnObject)
Handle_ShapeCustom_TrsfModification_DownCast = _ShapeCustom.Handle_ShapeCustom_TrsfModification_DownCast



